### ISSUE TITLE
Is it usable yet?

### ISSUE THREAD

**Issue by dchinmay2** [very-amused/mopidy-discord-rpc#1]
How do I use this?

**Comment by very-amused** [comment]
This project isn't in a usable state quite yet, I'll be sure to add usage instructions and mention them here when it is. Thanks for your interest.

**Comment by dchinmay2** [comment]
https://github.com/RayzrDev/discord-rpc-mpris this works well (after installing mopidy-mpris)

**Comment by very-amused** [comment]
I'm happy to say that this project is now ready for use, instructions are in [README.md](https://github.com/very-amused/mopidy-discord-rpc/blob/main/README.md).
